#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by Jupy Tools
# Kernel: Unknown
# Cells: 1 code, 0 markdown

# ────────────────────────────────────────────────────────────────────────
# %%  [1]

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

# -------------------------------------------------
# 1. Load and prepare data
# -------------------------------------------------
df = pd.read_csv("Concrete_Data.csv")

df.columns = [
    "Cement", "BlastFurnaceSlag", "FlyAsh", "Water",
    "Superplasticizer", "CoarseAggregate", "FineAggregate",
    "Age", "Strength"
]

X = df.drop("Strength", axis=1).values.astype(np.float32)
y = df["Strength"].values.astype(np.float32).reshape(-1, 1)

# Pad features to match required input_size=10
X = np.hstack([X, np.zeros((X.shape[0], 2), dtype=np.float32)])

# Make target 2-dimensional to match output_size=2
y = np.hstack([y, y])   # duplicate the strength column

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

X_train_t = torch.from_numpy(X_train)
y_train_t = torch.from_numpy(y_train)
X_test_t  = torch.from_numpy(X_test)
y_test_t  = torch.from_numpy(y_test)

train_loader = DataLoader(
    TensorDataset(X_train_t, y_train_t),
    batch_size=64,
    shuffle=True
)

# -------------------------------------------------
# 2. Define the model named 'my_mlp'
#    - First layer : input_size=10, hidden_size=20
#    - Final layer : hidden_size=20, output_size=2
# -------------------------------------------------
my_mlp = nn.Sequential(
    nn.Linear(10, 20),     # First layer: input_size=10 → hidden_size=20
    nn.ReLU(),
    nn.Linear(20, 2)       # Final layer: hidden_size=20 → output_size=2
)

print(my_mlp)

# -------------------------------------------------
# 3. Training
# -------------------------------------------------
criterion = nn.MSELoss()
optimizer = optim.Adam(my_mlp.parameters(), lr=0.01)

epochs = 500
print("\nTraining...")

for epoch in range(epochs):
    my_mlp.train()
    total_loss = 0.0

    for xb, yb in train_loader:
        optimizer.zero_grad()
        pred = my_mlp(xb)
        loss = criterion(pred, yb)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * xb.size(0)

    if (epoch + 1) % 100 == 0:
        avg_loss = total_loss / len(X_train)
        print(f"Epoch {epoch+1:3d} | Train MSE: {avg_loss:.4f}")

# -------------------------------------------------
# 4. Predict function + Evaluation
# -------------------------------------------------
def predict_relu(model, X):
    model.eval()
    with torch.no_grad():
        if isinstance(X, np.ndarray):
            X = torch.from_numpy(X.astype(np.float32))
        return model(X).numpy()

y_train_pred = predict_relu(my_mlp, X_train)
y_test_pred  = predict_relu(my_mlp, X_test)

print("\n=== Results ===")
print(f"Train RMSE : {np.sqrt(mean_squared_error(y_train, y_train_pred)):.3f}")
print(f"Test  RMSE : {np.sqrt(mean_squared_error(y_test,  y_test_pred)):.3f}")
print(f"Train R²   : {r2_score(y_train, y_train_pred):.4f}")
print(f"Test  R²   : {r2_score(y_test,  y_test_pred):.4f}")
