#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by Jupy Tools
# Kernel: Unknown
# Cells: 1 code, 0 markdown

# ────────────────────────────────────────────────────────────────────────
# %%  [1]

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

# -------------------------------------------------
# 1. Load and prepare data
# -------------------------------------------------
df = pd.read_csv("Concrete_Data.csv")

df.columns = [
    "Cement", "BlastFurnaceSlag", "FlyAsh", "Water",
    "Superplasticizer", "CoarseAggregate", "FineAggregate",
    "Age", "Strength"
]

X = df.drop("Strength", axis=1).values.astype(np.float32)
y = df["Strength"].values.astype(np.float32).reshape(-1, 1)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# Convert to tensors
X_train_t = torch.from_numpy(X_train)
y_train_t = torch.from_numpy(y_train)
X_test_t  = torch.from_numpy(X_test)
y_test_t  = torch.from_numpy(y_test)

train_loader = DataLoader(
    TensorDataset(X_train_t, y_train_t),
    batch_size=64,
    shuffle=True
)

# -------------------------------------------------
# 2. Two-layer ReLU model
# -------------------------------------------------
class TwoLayerReLU(nn.Module):
    def __init__(self, input_dim=8, hidden_dim=64, output_dim=1):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        h = self.relu(self.fc1(x))
        return self.fc2(h)

model = TwoLayerReLU(input_dim=8, hidden_dim=64, output_dim=1)

# -------------------------------------------------
# 3. Training
# -------------------------------------------------
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

epochs = 500
print("Training...")

for epoch in range(epochs):
    model.train()
    total_loss = 0.0
    
    for xb, yb in train_loader:
        optimizer.zero_grad()
        pred = model(xb)
        loss = criterion(pred, yb)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * xb.size(0)
    
    if (epoch + 1) % 100 == 0:
        avg_loss = total_loss / len(X_train)
        print(f"Epoch {epoch+1:3d} | Train MSE: {avg_loss:.4f}")

# -------------------------------------------------
# 4. Evaluation + predict function
# -------------------------------------------------
def predict_relu(model, X):
    """Predict using the trained two-layer ReLU model"""
    model.eval()
    with torch.no_grad():
        if isinstance(X, np.ndarray):
            X = torch.from_numpy(X.astype(np.float32))
        return model(X).numpy()

# Predictions
y_train_pred = predict_relu(model, X_train)
y_test_pred  = predict_relu(model, X_test)

print("\n=== Results ===")
print(f"Train RMSE : {np.sqrt(mean_squared_error(y_train, y_train_pred)):.3f} MPa")
print(f"Test  RMSE : {np.sqrt(mean_squared_error(y_test,  y_test_pred)):.3f} MPa")
print(f"Train R²   : {r2_score(y_train, y_train_pred):.4f}")
print(f"Test  R²   : {r2_score(y_test,  y_test_pred):.4f}")

# Example single prediction
sample = X_test[0:1]
pred = predict_relu(model, sample)
print(f"\nExample:")
print(f"True      : {y_test[0,0]:.2f} MPa")
print(f"Predicted : {pred[0,0]:.2f} MPa")
