#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by Jupy Tools
# Kernel: Unknown
# Cells: 1 code, 0 markdown

# ────────────────────────────────────────────────────────────────────────
# %%  [1]

import pandas as pd
import torch
import torch.nn as nn

# Load the dataset
df = pd.read_csv("Concrete_Data.csv")

# Separate inputs and target
inputs = df.iloc[:, :-1].values
target = df.iloc[:, -1].values

# Convert to tensors
X = torch.tensor(inputs, dtype=torch.float32)
y = torch.tensor(target, dtype=torch.float32).reshape(-1, 1)

# Two-layer linear model with ReLU
model = nn.Sequential(
    nn.Linear(8, 8),
    nn.ReLU(),
    nn.Linear(8, 1)
)

# Define prediction function
def predict_relu(x):
    return model(x)

# Use 4 samples
X_batch = X[:4]

# Generate predictions
y_pred = predict_relu(X_batch)

print(y_pred)
print(y_pred.shape)
