#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by Jupy Tools
# Kernel: Unknown
# Cells: 1 code, 0 markdown

# ────────────────────────────────────────────────────────────────────────
# %%  [1]

import pandas as pd
import torch
import torch.nn as nn

# Load the dataset
df = pd.read_csv("Concrete_Data.csv")

# Separate inputs and target
inputs = df.iloc[:, :-1].values
target = df.iloc[:, -1].values

# Convert to PyTorch tensors
X = torch.tensor(inputs, dtype=torch.float32)
y = torch.tensor(target, dtype=torch.float32).reshape(-1, 1)

# Create a two-layer linear network with no activation
model = nn.Sequential(
    nn.Linear(8, 8),
    nn.Linear(8, 1)
)

# Get model output
y_pred = model(X)

# Display output shape
print(y_pred.shape)
