#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by Jupy Tools
# Kernel: Unknown
# Cells: 1 code, 0 markdown

# ────────────────────────────────────────────────────────────────────────
# %%  [1]

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

# -------------------------------------------------
# 1. Load and prepare data
# -------------------------------------------------
df = pd.read_csv("Concrete_Data.csv")

df.columns = [
    "Cement", "BlastFurnaceSlag", "FlyAsh", "Water",
    "Superplasticizer", "CoarseAggregate", "FineAggregate",
    "Age", "Strength"
]

X = df.drop("Strength", axis=1).values.astype(np.float32)
y = df["Strength"].values.astype(np.float32).reshape(-1, 1)

# Adjust features to match required input size = 6
X = X[:, :6]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

X_train_t = torch.from_numpy(X_train)
y_train_t = torch.from_numpy(y_train)
X_test_t  = torch.from_numpy(X_test)
y_test_t  = torch.from_numpy(y_test)

train_loader = DataLoader(
    TensorDataset(X_train_t, y_train_t),
    batch_size=64,
    shuffle=True
)

# -------------------------------------------------
# 2. Custom MLP using nn.Module
#    Requirements:
#    - Class name: CustomMLPModel
#    - Exactly 3 linear layers
#    - Exactly 2 ReLU activations
#    - First layer  : Linear(6, 24)
#    - Second layer : Linear(24, 12)
#    - Output layer : Linear(12, 1)
# -------------------------------------------------
class CustomMLPModel(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.fc1 = nn.Linear(6, 24)       # First layer
        self.relu1 = nn.ReLU()            # 1st ReLU
        
        self.fc2 = nn.Linear(24, 12)      # Second layer
        self.relu2 = nn.ReLU()            # 2nd ReLU
        
        self.fc3 = nn.Linear(12, 1)       # Output layer
        
        self.dropout = nn.Dropout(0.2)

    def forward(self, x):
        x = self.relu1(self.fc1(x))
        x = self.dropout(x)
        
        x = self.relu2(self.fc2(x))
        x = self.dropout(x)
        
        x = self.fc3(x)
        return x

# Create the required model instance
my_mlp = CustomMLPModel()
print(my_mlp)

# -------------------------------------------------
# 3. Training
# -------------------------------------------------
criterion = nn.MSELoss()
optimizer = optim.Adam(my_mlp.parameters(), lr=0.005)

epochs = 400
print("\nTraining...")

for epoch in range(epochs):
    my_mlp.train()
    total_loss = 0.0

    for xb, yb in train_loader:
        optimizer.zero_grad()
        pred = my_mlp(xb)
        loss = criterion(pred, yb)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * xb.size(0)

    if (epoch + 1) % 100 == 0:
        avg_loss = total_loss / len(X_train)
        print(f"Epoch {epoch+1:3d} | Train MSE: {avg_loss:.4f}")

# -------------------------------------------------
# 4. Predict function + Evaluation
# -------------------------------------------------
def predict_relu(model, X):
    model.eval()
    with torch.no_grad():
        if isinstance(X, np.ndarray):
            X = torch.from_numpy(X.astype(np.float32))
        return model(X).numpy()

y_train_pred = predict_relu(my_mlp, X_train)
y_test_pred  = predict_relu(my_mlp, X_test)

print("\n=== Results ===")
print(f"Train RMSE : {np.sqrt(mean_squared_error(y_train, y_train_pred)):.3f} MPa")
print(f"Test  RMSE : {np.sqrt(mean_squared_error(y_test,  y_test_pred)):.3f} MPa")
print(f"Train R²   : {r2_score(y_train, y_train_pred):.4f}")
print(f"Test  R²   : {r2_score(y_test,  y_test_pred):.4f}")
