#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated by Jupy Tools
# Kernel: Unknown
# Cells: 1 code, 0 markdown

# ────────────────────────────────────────────────────────────────────────
# %%  [1]

import torch

# Define the input tensor
test_x = torch.tensor([-2.0, -1.0, 0.0, 1.0, 2.0])

# Manually implement Tanh
def my_tanh(x):
    return (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))

# Apply Tanh
y = my_tanh(test_x)

print(y)
